#!/usr/bin/env bun
/**
 * Prerender the landing at build time.
 *
 * Renders <Landing/> once — renderToStaticMarkup, no React on the wire — and
 * writes the markup into `landing-body.generated.ts` as a template with one
 * placeholder: @@INSTALL_COMMAND@@, swapped per request so a preview
 * deployment shows its own install command. The generated module is COMMITTED,
 * which is what keeps the Worker bundle free of react-dom/server; a unit gate
 * re-renders and fails when the committed body drifts from the component.
 *
 *   bun packages/cf-backend/scripts/prerender-landing.ts
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { renderToStaticMarkup } from 'react-dom/server';

import { Landing } from '../src/components/landing/Landing';
import { cliFilmFigure } from '../src/lib/cli-film';

const OUT = join(import.meta.dir, '..', 'src', 'lib', 'landing-body.generated.ts');

const body = renderToStaticMarkup(
  <Landing
    install="@@INSTALL_COMMAND@@"
    cliFilm={cliFilmFigure()}
  />,
);

const module = `/**
 * GENERATED by scripts/prerender-landing.ts — do not edit.
 *
 * <Landing/> rendered to static markup at build time (see this file's
 * generator for the why). One placeholder survives: @@INSTALL_COMMAND@@,
 * replaced per request by lib/public-pages. A parity gate re-renders the
 * component and fails when this drifts.
 */

export const LANDING_BODY = ${JSON.stringify(body)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, module);
console.log(`prerender-landing: wrote ${OUT} (${body.length} bytes of markup)`);
