import { SyntaxStyle } from '@opentui/core';

export const tuiColors = {
  bg: '#141009',
  panel: '#1d1610',
  panelStrong: '#241B12',
  panelDeep: '#18120b',
  selection: '#3a2b16',
  selectionDeep: '#2c2012',
  bubbleBg: '#2a2118',
  bubbleBorder: '#4a3a22',
  border: '#4a3a22',
  borderSubtle: '#33281a',
  borderMuted: '#5a472b',
  borderActive: '#E0A458',
  text: '#d8cdb8',
  textStrong: '#F5EFE6',
  textBright: '#FBF7F0',
  muted: '#8a7d68',
  accent: '#E0A458',
  accentStrong: '#F0CF9B',
  accentDeep: '#caa05a',
  blue: '#7d9bb5',
  green: '#88A06B',
  amber: '#E0A458',
  amberDeep: '#caa05a',
  red: '#E07A5F',
};

export const markdownSyntax = SyntaxStyle.fromStyles({
  text: { fg: tuiColors.text },
  paragraph: { fg: tuiColors.text },
  heading: { fg: tuiColors.textStrong, bold: true },
  strong: { fg: tuiColors.textStrong, bold: true },
  emphasis: { fg: tuiColors.text, italic: true },
  code: { fg: '#E8B97A', bg: '#241B12' },
  codespan: { fg: '#E8B97A', bg: '#241B12' },
  link: { fg: tuiColors.blue, underline: true },
  blockquote: { fg: tuiColors.muted, italic: true },
  list: { fg: tuiColors.text },
  list_item: { fg: tuiColors.text },
  table: { fg: tuiColors.text },
  hr: { fg: tuiColors.border },
});
