/**
 * Pure core of the FUSE capability/performance probe.
 *
 * Three consumers, one source of truth:
 *   - `probe.ts` runs inside the deployed container under bun and imports the
 *     byte generator, the FUSE wire packers and the syscall tables.
 *   - `scripts/bench-fuse-probe.ts` imports the report schemas and the verdict
 *     classifier, so the driver's PASS/NO_GO decision is the same code the
 *     tests pin.
 *   - `scripts/bench-fuse-probe.test.ts` pins every packing layout, the
 *     generator's determinism and each defect-detection class offline.
 *
 * Nothing here touches a filesystem, a process or a device: everything is a
 * function of its arguments. The side-effectful half lives in probe.ts.
 */
import * as v from 'valibot';

import { RangeReadIntentSchema, type RangeReadIntent } from '../../../packages/devbox/src/durability/contracts';
import type { RunIdentity } from './worker-contract';

// The Worker-facing contract (image identity, RunIdentity, route dispatch)
// lives in ./worker-contract so the workerd fixture and this bun-side module
// share one source; re-exported here so driver and tests keep one import.
export {
  CommandSchema, ImageIdentityError, RunIdentitySchema,
  SANDBOX_IMAGE, SANDBOX_IMAGE_VERSION, handleProbeOp, isAuthorized,
} from './worker-contract';
export type { ProbeBox, ProbeCommand, RunIdentity } from './worker-contract';

// ── reference content model ──────────────────────────────────────────────────

/** Deterministic seed for the whole synthetic tree. One seed means one
 *  expected-bytes function, which is what makes every read checkable. */
export const TREE_SEED = 0x5f00d;

/** The range-backed file: 32 MiB served in 128 KiB chunks, generated lazily.
 *  A candidate restore design must answer a slice of such a file without
 *  materializing it; this file is the instrument for that question. */
export const BIG_FILE_BYTES = 32 * 1024 * 1024;
export const CHUNK_BYTES = 128 * 1024;
export const BIG_FILE_CHUNKS = BIG_FILE_BYTES / CHUNK_BYTES;

/** xorshift32 stream, byte-wise little-endian. Pure and cheap: the daemon
 *  regenerates any chunk on demand instead of storing 32 MiB. */
export function canonicalChunk(seed: number, chunkIndex: number): Uint8Array {
  const out = new Uint8Array(CHUNK_BYTES);
  let state = (seed ^ Math.imul(chunkIndex + 1, 0x9e3779b1)) >>> 0;
  if (state === 0) state = 0xa5a5_5aa5;
  for (let offset = 0; offset < CHUNK_BYTES; offset += 4) {
    state ^= state << 13; state >>>= 0;
    state ^= state >>> 17;
    state ^= state << 5; state >>>= 0;
    out[offset] = state & 0xff;
    out[offset + 1] = (state >>> 8) & 0xff;
    out[offset + 2] = (state >>> 16) & 0xff;
    out[offset + 3] = (state >>> 24) & 0xff;
  }
  return out;
}

/** SHA-256 of one canonical chunk, hex. This is the trusted side of the
 *  integrity check: derived from the definition of the bytes, not from an
 *  in-memory copy that could rot the same way. */
export function chunkDigest(seed: number, chunkIndex: number): string {
  return sha256Hex(canonicalChunk(seed, chunkIndex));
}

/** SHA-256 of an arbitrary canonical byte range (chunk-aligned start assumed
 *  not; ranges are checked against regenerated bytes, not chunk digests). */
export function canonicalRange(seed: number, offset: number, length: number): Uint8Array {
  const out = new Uint8Array(length);
  const first = Math.floor(offset / CHUNK_BYTES);
  const last = Math.floor((offset + length - 1) / CHUNK_BYTES);
  let written = 0;
  for (let chunk = first; chunk <= last; chunk++) {
    const bytes = canonicalChunk(seed, chunk);
    const from = Math.max(offset, chunk * CHUNK_BYTES) - chunk * CHUNK_BYTES;
    const to = Math.min(offset + length, (chunk + 1) * CHUNK_BYTES) - chunk * CHUNK_BYTES;
    out.set(bytes.subarray(from, to), written);
    written += to - from;
  }
  return out;
}

export function sha256Hex(bytes: Uint8Array): string {
  const hasher = new Bun.CryptoHasher('sha256');
  hasher.update(bytes);
  return hasher.digest('hex');
}

/** What the serving path must do for every range: regenerate, hash, compare
 *  against the trusted derivation. Returns the reason a read is refused. */
export function verifyChunk(
  seed: number,
  chunkIndex: number,
  actual: Uint8Array,
  corrupt: boolean,
): { ok: true } | { ok: false; reason: string } {
  const expected = chunkDigest(seed, chunkIndex);
  const seen = corrupt ? sha256Hex(xorByte(actual)) : sha256Hex(actual);
  return seen === expected ? { ok: true } : { ok: false, reason: `chunk ${chunkIndex} digest mismatch` };
}

function xorByte(bytes: Uint8Array): Uint8Array {
  const copy = new Uint8Array(bytes.length);
  copy.set(bytes);
  copy[0] ^= 0xff;
  return copy;
}

// ── RangeReadIntent consumption ──────────────────────────────────────────────

/** Every measured range read becomes one shared-contract intent record: same
 *  shape the durability plane signs before fetching a payload range. The
 *  driver validates these against `RangeReadIntentSchema` before trusting a
 *  single latency number attached to them. */
export function buildRangeIntent(input: {
  operationId: string;
  attemptId: string;
  exactKey: string;
  byteOffset: number;
  byteLength: number;
}): RangeReadIntent {
  return {
    operationId: input.operationId,
    attemptId: input.attemptId,
    boxId: 'fuse-ro-reference',
    epoch: '0',
    exactKey: input.exactKey,
    method: 'GET',
    byteOffset: String(input.byteOffset),
    byteLength: String(input.byteLength),
    sha256: sha256Hex(canonicalRange(TREE_SEED, input.byteOffset, input.byteLength)),
    expiresAt: '0',
  };
}

export { RangeReadIntentSchema };
export type { RangeReadIntent };

// ── syscall surface ───────────────────────────────────────────────────────────

/** Direct syscall numbers. x86-64 and aarch64 differ except for openat2,
 *  which postdates the generic-numbering split. */
export interface SyscallNumbers {
  openat2: number;
  openat: number;
  mount: number;
  umount2: number;
  capget: number;
}

export const SYSCALL_TABLE = {
  x64: { openat2: 437, openat: 257, mount: 165, umount2: 166, capget: 125 },
  arm64: { openat2: 437, openat: 56, mount: 40, umount2: 39, capget: 90 },
} as const satisfies Record<string, SyscallNumbers>;

export function syscallNumbers(arch: string): SyscallNumbers {
  return arch === 'arm64' ? SYSCALL_TABLE.arm64 : SYSCALL_TABLE.x64;
}

export const RESOLVE_BENEATH = 0x02;
export const RESOLVE_NO_SYMLINKS = 0x08;
export const OPEN_HOW_SIZE = 24;

/** struct open_how { u64 flags; u64 mode; u64 resolve; } */
export function packOpenHow(flags: bigint, mode: bigint, resolve: bigint): Buffer {
  const buf = Buffer.alloc(OPEN_HOW_SIZE);
  buf.writeBigUInt64LE(flags, 0);
  buf.writeBigUInt64LE(mode, 8);
  buf.writeBigUInt64LE(resolve, 16);
  return buf;
}

/** struct __user_cap_header_struct { u32 version; i32 pid; } and one
 *  __user_cap_data_struct triple per 32 capabilities (v3 => two triples). */
export const CAP_V3_VERSION = 0x20080522;
export const CAP_USER_HEADER_SIZE = 8;
export const CAP_DATA_SIZE = 12;
export const CAP_SYS_ADMIN_BIT = 21;

export const CAPABILITY_NAMES: readonly string[] = [
  'CHOWN', 'DAC_OVERRIDE', 'DAC_READ_SEARCH', 'FOWNER', 'FSETID', 'KILL',
  'SETGID', 'SETUID', 'SETPCAP', 'LINUX_IMMUTABLE', 'NET_BIND_SERVICE',
  'NET_BROADCAST', 'NET_ADMIN', 'NET_RAW', 'IPC_LOCK', 'IPC_OWNER',
  'SYS_MODULE', 'SYS_RAWIO', 'SYS_CHROOT', 'SYS_PTRACE', 'SYS_PACCT',
  'SYS_ADMIN', 'SYS_BOOT', 'SYS_NICE', 'SYS_RESOURCE', 'SYS_TIME',
  'SYS_TTY_CONFIG', 'MKNOD', 'LEASE', 'AUDIT_WRITE', 'AUDIT_CONTROL',
  'SETFCAP', 'MAC_OVERRIDE', 'MAC_ADMIN', 'SYSLOG', 'WAKE_ALARM',
  'BLOCK_SUSPEND', 'AUDIT_READ', 'PERFMON', 'BPF', 'CHECKPOINT_RESTORE',
];

/** Full v3 decode across both capability words. The container reports two
 *  u32 pairs; the honest decoder walks both. */
export interface CapabilityDecode {
  effective: string[];
  sysAdmin: boolean;
}

export function decodeCapabilitiesV3(words: readonly [number, number, number, number, number, number]): CapabilityDecode {
  const effLo = words[0] ?? 0;
  const effHi = words[1] ?? 0;
  const names: string[] = [];
  for (let bit = 0; bit < CAPABILITY_NAMES.length; bit++) {
    const word = bit < 32 ? effLo : effHi;
    const name = CAPABILITY_NAMES[bit];
    if (name !== undefined && (word & (1 << (bit % 32))) !== 0) names.push(name);
  }
  return { effective: names, sysAdmin: (effLo & (1 << 21)) !== 0 };
}

const ERRNO_NAMES = {
  1: 'EPERM', 2: 'ENOENT', 4: 'EINTR', 5: 'EIO', 6: 'ENXIO', 9: 'EBADF',
  11: 'EAGAIN', 12: 'ENOMEM', 13: 'EACCES', 17: 'EEXIST', 18: 'EXDEV',
  20: 'ENOTDIR', 21: 'EISDIR', 22: 'EINVAL', 24: 'EMFILE', 25: 'ENOTTY',
  26: 'ETXTBSY', 27: 'EFBIG', 28: 'ENOSPC', 30: 'EROFS', 31: 'EMLINK',
  34: 'ERANGE', 36: 'ENAMETOOLONG', 38: 'ENOSYS', 39: 'ENOTEMPTY',
  40: 'ELOOP', 61: 'ENODATA', 75: 'EOVERFLOW', 84: 'EILSEQ',
  88: 'ENOTSOCK', 95: 'EOPNOTSUPP', 116: 'ESTALE',
} as const;

const ERRNO_BY_CODE = new Map<number, string>(
  Object.entries(ERRNO_NAMES).map(([code, name]) => [Number(code), name]),
);

export function errnoName(errno: number | undefined | null): string | undefined {
  if (errno === undefined || errno === null) return undefined;
  return ERRNO_BY_CODE.get(-errno) ?? ERRNO_BY_CODE.get(errno) ?? `errno-${errno}`;
}

// ── FUSE wire protocol (/dev/fuse ABI 7.x) ───────────────────────────────────

export const FUSE_OPCODES = {
  LOOKUP: 1, FORGET: 2, GETATTR: 3, SETATTR: 4, READLINK: 5, SYMLINK: 6,
  MKNOD: 8, MKDIR: 9, UNLINK: 10, RMDIR: 11, RENAME: 12, LINK: 13,
  OPEN: 14, READ: 15, WRITE: 16, STATFS: 17, RELEASE: 18, FSYNC: 20,
  SETXATTR: 21, GETXATTR: 22, LISTXATTR: 23, REMOVEXATTR: 24, FLUSH: 25,
  INIT: 26, OPENDIR: 27, READDIR: 28, RELEASEDIR: 29, FSYNCDIR: 30,
  GETLK: 31, SETLK: 32, ACCESS: 33, CREATE: 34, INTERRUPT: 35, BMAP: 36,
  DESTROY: 37, IOCTL: 39, POLL: 40, BATCH_FORGET: 42, READDIRPLUS: 43,
} as const;

export const IN_HEADER_SIZE = 40;
export const OUT_HEADER_SIZE = 16;

export const INIT_FLAGS = {
  ASYNC_READ: 1 << 0,
  BIG_WRITES: 1 << 5,
  PARALLEL_DIROPS: 1 << 21,
  MAX_PAGES: 1 << 22,
} as const;

export const FUSE_PROTOCOL_MAJOR = 7;
export const FUSE_PROTOCOL_MINOR_MAX = 38;

/** struct fuse_attr — 88 bytes. */
export const FUSE_ATTR_SIZE = 88;

export interface FuseAttrInput {
  ino: number;
  size: number;
  mode: number;
  nlink: number;
}

/** Layout: ino u64, size u64, blocks u64, atime u64, mtime u64, ctime u64,
 *  then ten u32s (three nsecs, mode, nlink, uid, gid, rdev, blksize, flags). */
export function packFuseAttr(input: FuseAttrInput, into: Buffer, offset: number): void {
  const blocks = Math.ceil(input.size / 512);
  into.writeBigUInt64LE(BigInt(input.ino), offset);
  into.writeBigUInt64LE(BigInt(input.size), offset + 8);
  into.writeBigUInt64LE(BigInt(blocks), offset + 16);
  into.writeBigUInt64LE(1700000000n, offset + 24);
  into.writeBigUInt64LE(1700000000n, offset + 32);
  into.writeBigUInt64LE(1700000000n, offset + 40);
  into.writeUInt32LE(0, offset + 48);
  into.writeUInt32LE(0, offset + 52);
  into.writeUInt32LE(0, offset + 56);
  into.writeUInt32LE(input.mode, offset + 60);
  into.writeUInt32LE(input.nlink, offset + 64);
  into.writeUInt32LE(0, offset + 68);
  into.writeUInt32LE(0, offset + 72);
  into.writeUInt32LE(0, offset + 76);
  into.writeUInt32LE(4096, offset + 80);
  into.writeUInt32LE(0, offset + 84);
}

/** struct fuse_entry_out: nodeid u64, generation u64, entry_valid u64,
 *  attr_valid u64, two validity nsecs u32, then attr(88). */
export const ENTRY_OUT_SIZE = 128;

export function packEntryOut(nodeid: number, attr: FuseAttrInput): Buffer {
  const buf = Buffer.alloc(ENTRY_OUT_SIZE);
  buf.writeBigUInt64LE(BigInt(nodeid), 0);
  buf.writeBigUInt64LE(0n, 8);
  // Zero validity windows keep every lookup observable.
  buf.writeBigUInt64LE(0n, 16);
  buf.writeBigUInt64LE(0n, 24);
  buf.writeUInt32LE(0, 32);
  buf.writeUInt32LE(0, 36);
  packFuseAttr(attr, buf, 40);
  return buf;
}

/** struct fuse_attr_out: attr_valid u64, attr_valid_nsec u32, dummy u32,
 *  attr(88). */
export const GETATTR_OUT_SIZE = 104;

export function packGetattrOut(attr: FuseAttrInput): Buffer {
  const buf = Buffer.alloc(GETATTR_OUT_SIZE);
  buf.writeBigUInt64LE(0n, 0);
  buf.writeUInt32LE(0, 8);
  buf.writeUInt32LE(0, 12);
  packFuseAttr(attr, buf, 16);
  return buf;
}

/** struct fuse_open_out: fh u64, open_flags u32, padding u32. */
export const OPEN_OUT_SIZE = 16;

export function packOpenOut(fh: bigint): Buffer {
  const buf = Buffer.alloc(OPEN_OUT_SIZE);
  buf.writeBigUInt64LE(fh, 0);
  buf.writeUInt32LE(0, 8);
  buf.writeUInt32LE(0, 12);
  return buf;
}

/** struct fuse_dirent: ino u64, off u64, namelen u32, type u32, name padded
 *  to 8-byte alignment. Names are NOT NUL-terminated. */
export function packDirent(ino: number, cookie: number, type: number, name: string): Buffer {
  const nameBytes = Buffer.from(name, 'utf8');
  const total = align8(24 + nameBytes.length);
  const buf = Buffer.alloc(total);
  buf.writeBigUInt64LE(BigInt(ino), 0);
  buf.writeBigUInt64LE(BigInt(cookie), 8);
  buf.writeUInt32LE(nameBytes.length, 16);
  buf.writeUInt32LE(type, 20);
  nameBytes.copy(buf, 24);
  return buf;
}

export function align8(n: number): number {
  return (n + 7) & ~7;
}

/** struct fuse_statfs_out payload: five u64s, four named u32s, six spare. */
export const STATFS_OUT_SIZE = 80;

export function packStatfs(files: number): Buffer {
  const buf = Buffer.alloc(STATFS_OUT_SIZE);
  buf.writeBigUInt64LE(BigInt(1_048_576), 0); // blocks
  buf.writeBigUInt64LE(BigInt(1_048_576), 8); // bfree
  buf.writeBigUInt64LE(BigInt(1_048_576), 16); // bavail
  buf.writeBigUInt64LE(BigInt(files), 24);
  buf.writeBigUInt64LE(BigInt(files), 32);
  buf.writeUInt32LE(4096, 40); // bsize
  buf.writeUInt32LE(255, 44); // namelen
  buf.writeUInt32LE(4096, 48); // frsize
  return buf;
}

/** struct fuse_init_out payload — 64 bytes including the spare tail. */
export const INIT_OUT_PAYLOAD_SIZE = 64;

export function packInitOut(kernelMinor: number, kernelFlags: number, maxReadahead: number): Buffer {
  const minor = Math.min(kernelMinor, FUSE_PROTOCOL_MINOR_MAX);
  const flags =
    INIT_FLAGS.ASYNC_READ | INIT_FLAGS.BIG_WRITES |
    INIT_FLAGS.PARALLEL_DIROPS | INIT_FLAGS.MAX_PAGES;
  const buf = Buffer.alloc(INIT_OUT_PAYLOAD_SIZE);
  buf.writeUInt32LE(FUSE_PROTOCOL_MAJOR, 0);
  buf.writeUInt32LE(minor, 4);
  buf.writeUInt32LE(maxReadahead, 8);
  buf.writeUInt32LE(flags, 12);
  buf.writeUInt16LE(0, 16); // max_background
  buf.writeUInt16LE(0, 18); // congestion_threshold
  buf.writeUInt32LE(1024 * 1024, 20); // max_write
  buf.writeUInt32LE(1, 24); // time_gran
  buf.writeUInt16LE(256, 28); // max_pages
  buf.writeUInt16LE(0, 30); // map_alignment
  buf.writeUInt32LE(0, 32); // flags2
  buf.writeUInt32LE(0, 36); // max_stack_depth
  buf.writeUInt16LE(0, 40); // request_timeout
  void kernelFlags;
  return buf;
}

/** fuse_out_header: len u32, error i32, unique u64. */
export function packOutHeader(payloadLength: number, unique: bigint, error = 0): Buffer {
  const header = Buffer.alloc(OUT_HEADER_SIZE);
  header.writeUInt32LE(OUT_HEADER_SIZE + payloadLength, 0);
  header.writeInt32LE(error, 4);
  header.writeBigUInt64LE(unique, 8);
  return header;
}

/** Mount option string for one FUSE mount, both privilege paths. */
export function fuseMountOptions(fd: number, uid: number, gid: number, extras: readonly string[]): string {
  return [
    `fd=${fd}`,
    'rootmode=40000',
    `user_id=${uid}`,
    `group_id=${gid}`,
    ...extras,
  ].join(',');
}

// ── statistics ────────────────────────────────────────────────────────────────

export interface LatencySummary {
  readonly n: number;
  readonly minMs: number;
  readonly p50Ms: number;
  readonly p95Ms: number;
  readonly maxMs: number;
  readonly meanMs: number;
}

export const LatencySummarySchema = v.looseObject({
  n: v.number(),
  minMs: v.number(),
  p50Ms: v.number(),
  p95Ms: v.number(),
  maxMs: v.number(),
  meanMs: v.number(),
});

export function summarizeLatencies(samplesMs: readonly number[]): LatencySummary | undefined {
  if (samplesMs.length === 0) return undefined;
  const sorted = [...samplesMs].sort((a, b) => a - b);
  const sum = sorted.reduce((total, value) => total + value, 0);
  const percentile = (p: number): number =>
    sorted[Math.min(sorted.length - 1, Math.ceil(p * sorted.length) - 1)]!;
  return {
    n: sorted.length,
    minMs: sorted[0]!,
    p50Ms: percentile(0.5),
    p95Ms: percentile(0.95),
    maxMs: sorted.at(-1)!,
    meanMs: sum / sorted.length,
  };
}

/**
 * Is bring-up cost dominated by an O(entries) term?
 *
 * Definitional, not a tuned threshold: fit t = a + b·n over the three sample
 * sizes by least squares; call bring-up eager when the fitted per-entry term
 * at the largest tree is more than 3× the intercept — i.e. the linear term
 * dominates whatever fixed cost exists. A lazy daemon (b≈0) never trips this;
 * download-then-index bootstrap does.
 */
export function classifyBootstrap(samples: readonly { entries: number; ms: number }[]): {
  eager: boolean;
  interceptMs: number;
  msPerEntry: number;
  largestEntries: number;
} | undefined {
  if (samples.length < 3) return undefined;
  const n = samples.length;
  const sumX = samples.reduce((t, s) => t + s.entries, 0);
  const sumY = samples.reduce((t, s) => t + s.ms, 0);
  const sumXX = samples.reduce((t, s) => t + s.entries ** 2, 0);
  const sumXY = samples.reduce((t, s) => t + s.entries * s.ms, 0);
  const denominator = n * sumXX - sumX ** 2;
  if (denominator === 0) return undefined;
  const b = (n * sumXY - sumX * sumY) / denominator;
  const a = (sumY - b * sumX) / n;
  const largest = Math.max(...samples.map((s) => s.entries));
  return { eager: Math.abs(b) * largest > 3 * Math.abs(a) && b > 0, interceptMs: a, msPerEntry: b, largestEntries: largest };
}

// ── stage reports ─────────────────────────────────────────────────────────────

const BinaryCensusRowSchema = v.looseObject({
  name: v.string(),
  path: v.nullable(v.string()),
  availability: v.picklist(['available', 'no_go']),
});

const SyscallProbeRowSchema = v.looseObject({
  name: v.string(),
  nr: v.number(),
  outcome: v.string(),
  errnoName: v.optional(v.nullable(v.string())),
  detail: v.optional(v.string()),
});

export const CensusSchema = v.looseObject({
  uid: v.number(),
  gid: v.number(),
  arch: v.string(),
  kernelRelease: v.string(),
  mountNamespace: v.string(),
  capabilities: v.looseObject({
    names: v.array(v.string()),
    sysAdmin: v.boolean(),
  }),
  seccomp: v.looseObject({
    mode: v.number(),
    filters: v.number(),
  }),
  devFuse: v.looseObject({
    exists: v.boolean(),
    detail: v.optional(v.string()),
  }),
  binaries: v.array(BinaryCensusRowSchema),
  kernelFilesystems: v.looseObject({
    fuse: v.boolean(),
    overlay: v.boolean(),
    erofs: v.boolean(),
  }),
  syscalls: v.array(SyscallProbeRowSchema),
  /** Third-party read-only image formats: availability only. Never installed,
   *  never pretended present — absence is the finding when absence is true. */
  imageFormats: v.array(BinaryCensusRowSchema),
});
export type Census = v.InferOutput<typeof CensusSchema>;

export const Openat2ReportSchema = v.looseObject({
  syscallNr: v.number(),
  supported: v.boolean(),
  supportErrnoName: v.optional(v.nullable(v.string())),
  beneathPositive: v.looseObject({ ok: v.boolean(), detail: v.optional(v.string()) }),
  absoluteEscape: v.looseObject({ blocked: v.boolean(), errnoName: v.optional(v.string()) }),
  dotDotEscape: v.looseObject({ blocked: v.boolean(), errnoName: v.optional(v.string()) }),
  symlinkAncestorNoSymlinks: v.looseObject({ blocked: v.boolean(), errnoName: v.optional(v.string()) }),
  symlinkAncestorBeneathOnly: v.looseObject({ blocked: v.boolean(), errnoName: v.optional(v.string()) }),
  deterministicSequence: v.looseObject({
    plainEscaped: v.boolean(),
    openat2Blocked: v.boolean(),
  }),
  race: v.looseObject({
    swaps: v.number(),
    resolutions: v.number(),
    escapesObserved: v.number(),
    controlPlainEscapes: v.number(),
    outcomes: v.record(v.string(), v.number()),
  }),
});
export type Openat2Report = v.InferOutput<typeof Openat2ReportSchema>;

const MountAttemptSchema = v.looseObject({
  label: v.string(),
  route: v.picklist(['direct-syscall', 'fusermount']),
  ok: v.boolean(),
  errnoName: v.optional(v.nullable(v.string())),
  syscallNr: v.optional(v.number()),
  detail: v.optional(v.string()),
});

export const RangeReadRecordSchema = v.strictObject({
  ...RangeReadIntentSchema.entries,
  latencyMs: v.number(),
  verified: v.boolean(),
});

export const Stage1ReportSchema = v.looseObject({
  stage: v.literal('stage1'),
  attemptId: v.string(),
  startedAt: v.string(),
  finishedAt: v.string(),
  census: CensusSchema,
  openat2: Openat2ReportSchema,
  mountAttempts: v.array(MountAttemptSchema),
  mounted: v.boolean(),
  mountpoint: v.optional(v.string()),
  bootstrapSamples: v.array(v.looseObject({ entries: v.number(), ms: v.number() })),
  coldRootChallengeMs: v.array(v.number()),
  firstStatRead: v.array(v.looseObject({ statMs: v.number(), readMs: v.number(), bytes: v.number() })),
  workingSet: v.optional(v.looseObject({
    files: v.number(),
    iterations: v.number(),
    fuse: v.optional(LatencySummarySchema),
    native: v.optional(LatencySummarySchema),
  })),
  fullWalk: v.optional(v.looseObject({
    fuseFiles: v.number(),
    fuseMs: v.number(),
    nativeFiles: v.number(),
    nativeMs: v.number(),
  })),
  rangeReads: v.array(RangeReadRecordSchema),
  cache: v.optional(v.looseObject({
    reps: v.number(),
    missP50Ms: v.number(),
    hitP50Ms: v.number(),
  })),
  integrity: v.looseObject({
    poisonChunk: v.number(),
    refused: v.boolean(),
    servedWrongBytes: v.boolean(),
    errnoName: v.optional(v.nullable(v.string())),
    digestRefusal: v.looseObject({ refused: v.boolean(), errnoName: v.optional(v.nullable(v.string())) }),
  }),
  links: v.looseObject({
    symlinkResolvedContentOk: v.boolean(),
    lstatIsLink: v.boolean(),
    hardlinkSameInoAndNlink2: v.boolean(),
  }),
  execMetadata: v.looseObject({
    mode0755Preserved: v.boolean(),
    execAttempted: v.boolean(),
    execOk: v.boolean(),
    note: v.optional(v.string()),
  }),
  overlay: v.looseObject({
    attempted: v.boolean(),
    composed: v.boolean(),
    readVerified: v.optional(v.boolean()),
    errnoName: v.optional(v.nullable(v.string())),
  }),
  mountsPresentAtExit: v.array(v.string()),
});
export type Stage1Report = v.InferOutput<typeof Stage1ReportSchema>;

/** Writable FUSE is a separate, stronger stage. It uses the image's pinned
 * C/libfuse build; the earlier raw-Bun read-only stage remains its control. */
export const Stage3ReportSchema = v.looseObject({
  stage: v.literal('stage3'),
  protocol: v.looseObject({
    requested: v.literal('7.39'),
    kernelHeader: v.nullable(v.looseObject({
      libfuse: v.literal('3.17.1'),
      kernel: v.looseObject({ major: v.literal(7), minor: v.number() }),
      constants: v.looseObject({
        directIoAllowMmap: v.literal(68_719_476_736),
        openDirectIo: v.literal(1),
      }),
      headers: v.looseObject({
        fuse_kernel_h: v.string(),
        fuse_lowlevel_h: v.string(),
        sourceSha256: v.string(),
      }),
    })),
  }),
  mutation: v.picklist([
    'none',
    'reply-before-log',
    'fence-closes-request-loop',
    'omit-msync',
    'post-fence-contamination',
    'intent-fsync-failure',
    'result-fsync-failure',
    'restart-truncation',
    'skip-recovery',
  ]),
  mounted: v.boolean(),
  directIoMmap: v.boolean(),
  preStore: v.boolean(),
  duringStore: v.boolean(),
  postStore: v.boolean(),
  forkedMapper: v.boolean(),
  continuousDirtying: v.boolean(),
  ordinaryWrites: v.boolean(),
  continuousDirtyBeforeFenceClosed: v.boolean(),
  continuousDirtyAfterFenceComplete: v.boolean(),
  msyncCalled: v.boolean(),
  controlFenceOk: v.boolean(),
  fsyncOk: v.boolean(),
  intentJournalDurable: v.boolean(),
  resultJournalDurable: v.boolean(),
  intentFsyncFailureRefused: v.boolean(),
  resultFsyncFailureRefused: v.boolean(),
  restartRemountOk: v.boolean(),
  restartOpenedExistingBacking: v.boolean(),
  restartRemountReadOk: v.boolean(),
  restartTruncationRefused: v.boolean(),
  restartDaemonKilled: v.boolean(),
  restartDeadMountDetached: v.boolean(),
  restartJournalReconciled: v.boolean(),
  crashCutAfterIntent: v.boolean(),
  journalPendingEmpty: v.boolean(),
  recoveryAbortDurable: v.boolean(),
  pendingEffectExcluded: v.boolean(),
  fenceClosed: v.boolean(),
  fenceDrained: v.boolean(),
  postWriteAfterFenceCut: v.boolean(),
  designatedWaiterResultAfterFenceCut: v.boolean(),
  noWritesAdmittedWhileClosed: v.boolean(),
  prefixReplayOk: v.boolean(),
  prePrefixIncluded: v.boolean(),
  excludedWritesAbsentFromPrefix: v.boolean(),
  finalBackingAllWrites: v.boolean(),
  requestLoopServedAfterFence: v.boolean(),
  backingOrderOk: v.boolean(),
  orderedLog: v.boolean(),
  loggedBeforeReply: v.boolean(),
  controlFenceObserved: v.boolean(),
  postFenceBeforeCompletion: v.boolean(),
  watchdogDeadlock: v.boolean(),
  finalUnmountOk: v.boolean(),
  daemonExitOk: v.boolean(),
  cleanupPathsRemoved: v.boolean(),
  mountResidueAbsent: v.boolean(),
  pathResidueAbsent: v.boolean(),
  reapBounded: v.boolean(),
  linearizable: v.boolean(),
});
export type Stage3Report = v.InferOutput<typeof Stage3ReportSchema>;

export const Stage2ReportSchema = v.looseObject({
  stage: v.literal('stage2'),
  attemptId: v.string(),
  startedAt: v.string(),
  finishedAt: v.string(),
  restartResidue: v.looseObject({
    priorInstanceMountLines: v.array(v.string()),
    freshInstanceClean: v.boolean(),
  }),
  remountOk: v.boolean(),
  stuckMountDrill: v.looseObject({
    hungDetected: v.boolean(),
    forcedUnmountOk: v.boolean(),
  }),
  cleanup: v.looseObject({
    unmountOk: v.boolean(),
    residueMounts: v.array(v.string()),
    strayDaemonProcesses: v.number(),
    backingDirsRemoved: v.boolean(),
    replayClean: v.boolean(),
  }),
});
export type Stage2Report = v.InferOutput<typeof Stage2ReportSchema>;

// ── verdict classification ───────────────────────────────────────────────────

/** Typed NO_GO kinds. Each names the platform premise that failed, so a
 *  consumer can branch on the reason without parsing prose. */
export type NoGoKind =
  | 'fuse-device-absent'
  | 'mount-refused'
  | 'runtime-crash'
  | 'openat2-unavailable'
  | 'image-mismatch'
  | 'mmap-not-linearizable';

export interface NoGoReason {
  readonly kind: NoGoKind;
  readonly detail: string;
}

export type DetectionKind =
  | 'eager-bootstrap'
  | 'range-integrity-missing'
  | 'digest-refusal-missing'
  | 'mount-residue'
  | 'escape-observed';

export interface Detection {
  readonly kind: DetectionKind;
  readonly detail: string;
}

export interface ProbeVerdict {
  /** PASS with measured evidence, DEFECT when a detection class fired, or
   *  typed NO_GO when the question could not even be asked. */
  readonly outcome: 'pass' | 'defect' | 'no_go';
  readonly noGo: readonly NoGoReason[];
  readonly detections: readonly Detection[];
}

/** The openat2 materialization capability gets its own sub-verdict, because
 *  its availability is independent of whether FUSE mounts work. */
export function classifyMaterialization(openat2: Openat2Report): ProbeVerdict {
  const detections: Detection[] = [];
  if (openat2.race.escapesObserved > 0) {
    detections.push({
      kind: 'escape-observed',
      detail: `openat2 RESOLVE_BENEATH|RESOLVE_NO_SYMLINKS returned outside-root content `
        + `${openat2.race.escapesObserved} time(s) under concurrent symlink swaps`,
    });
  }
  if (!openat2.supported) {
    return {
      outcome: 'no_go',
      noGo: [{
        kind: 'openat2-unavailable',
        detail: `direct syscall openat2 unsupported (${openat2.supportErrnoName ?? 'no errno'})`,
      }],
      detections,
    };
  }
  return { outcome: detections.length === 0 ? 'pass' : 'defect', noGo: [], detections };
}

/** This stage proves a daemon-owned control fence, not a FUSE syncfs request.
 * Admission closure makes writes that arrive during the fence wait and log
 * post-cut after reopening; prefix reconstruction proves none entered the cut. */
export function classifyWritableMmap(stage3: Stage3Report | undefined): ProbeVerdict {
  if (stage3 === undefined) {
    return {
      outcome: 'no_go',
      noGo: [{ kind: 'mmap-not-linearizable', detail: 'writable mmap stage produced no evidence' }],
      detections: [],
    };
  }
  const required: ReadonlyArray<readonly [string, boolean]> = [
    ['header-checked libfuse ABI', stage3.protocol.kernelHeader !== null],
    ['mount', stage3.mounted],
    ['DIRECT_IO_ALLOW_MMAP + MAP_SHARED', stage3.directIoMmap],
    ['pre-fence MAP_SHARED store', stage3.preStore],
    ['post-fence MAP_SHARED store', stage3.postStore],
    ['msync', stage3.msyncCalled],
    ['daemon-owned Unix control fence', stage3.controlFenceOk && stage3.controlFenceObserved],
    ['admission closed and admitted writes drained', stage3.fenceClosed && stage3.fenceDrained],
    ['write submitted after closure logs post-cut', stage3.postWriteAfterFenceCut],
    ['designated blocked writer result follows the immutable cut', stage3.designatedWaiterResultAfterFenceCut],
    ['immutable prefix replay from logged WRITE payloads', stage3.prefixReplayOk
      && stage3.prePrefixIncluded && stage3.excludedWritesAbsentFromPrefix],
    ['durable journal INTENT before mutation', stage3.intentJournalDurable],
    ['durable journal RESULT after mutation', stage3.resultJournalDurable],
    ['FUSE_FSYNC', stage3.fsyncOk],
    ['forked MAP_SHARED mapper', stage3.forkedMapper],
    ['continuous dirtying spans the cut', stage3.continuousDirtying
      && stage3.continuousDirtyBeforeFenceClosed && stage3.continuousDirtyAfterFenceComplete],
    ['concurrent ordinary writes', stage3.ordinaryWrites],
    ['request loop served after admission reopened', stage3.requestLoopServedAfterFence],
    ['no post-fence payload before completion or deadlock', !stage3.postFenceBeforeCompletion
      && !stage3.watchdogDeadlock],
    ['restart opened existing backing and remounted bytes', stage3.restartRemountOk
      && stage3.restartOpenedExistingBacking && stage3.restartRemountReadOk
      && stage3.restartDaemonKilled && stage3.restartDeadMountDetached
      && stage3.restartJournalReconciled && stage3.crashCutAfterIntent
      && stage3.journalPendingEmpty && stage3.recoveryAbortDurable
      && stage3.pendingEffectExcluded && stage3.backingOrderOk && stage3.finalBackingAllWrites],
    ['final unmount, daemon exit, and residue cleanup', stage3.finalUnmountOk
      && stage3.daemonExitOk && stage3.reapBounded && stage3.cleanupPathsRemoved
      && stage3.mountResidueAbsent && stage3.pathResidueAbsent],
    ['probe conclusion', stage3.linearizable],
  ];
  const absent = required.filter(([, holds]) => !holds).map(([name]) => name);
  if (stage3.mutation !== 'none') absent.push(`negative mutation ${stage3.mutation} did not run as the control`);
  return absent.length === 0
    ? { outcome: 'pass', noGo: [], detections: [] }
    : {
        outcome: 'no_go',
        noGo: [{
          kind: 'mmap-not-linearizable',
          detail: `writable FUSE mmap/barrier evidence failed: ${absent.join(', ')}`,
        }],
        detections: [],
      };
}
export type WritableMmapMutation = Exclude<Stage3Report['mutation'], 'none'>;

/** Every mutation is a separate real C invocation. Its exit/report pair stays
 * with the artifact so a control cannot be summarised into an uncheckable bit. */
export interface WritableMmapControl {
  readonly mutation: WritableMmapMutation;
  readonly exitCode: number;
  readonly report: Stage3Report;
  readonly verdict: ProbeVerdict;
}
/** A control must expose the particular invariant it breaks. The mutation
 * label alone is not evidence; otherwise a binary could report a generic
 * failure without exercising the intended negative path. */
export function mutationRefusalObserved(report: Stage3Report): boolean {
  switch (report.mutation) {
    case 'reply-before-log':
      return !report.loggedBeforeReply;
    case 'fence-closes-request-loop':
      return !report.postStore;
    case 'omit-msync':
      return !report.msyncCalled;
    case 'post-fence-contamination':
      return !report.excludedWritesAbsentFromPrefix && !report.prefixReplayOk;
    case 'intent-fsync-failure':
      return !report.intentJournalDurable && report.intentFsyncFailureRefused;
    case 'result-fsync-failure':
      return !report.resultJournalDurable && report.resultFsyncFailureRefused;
    case 'restart-truncation':
      return !report.restartRemountReadOk && report.restartTruncationRefused;
    case 'skip-recovery':
      return !report.journalPendingEmpty && !report.recoveryAbortDurable && !report.pendingEffectExcluded;
    case 'none':
      return false;
  }
}


export function classifyWritableMmapControls(
  controls: readonly WritableMmapControl[] | undefined,
): ProbeVerdict {
  const expected: readonly WritableMmapMutation[] = [
    'reply-before-log',
    'fence-closes-request-loop',
    'omit-msync',
    'post-fence-contamination',
    'intent-fsync-failure',
    'result-fsync-failure',
    'restart-truncation',
    'skip-recovery',
  ];
  const failures: string[] = expected.filter((mutation) => {
    const matches = controls?.filter((candidate) => candidate.mutation === mutation) ?? [];
    const control = matches[0];
    return matches.length !== 1 || control === undefined || control.exitCode !== 86
      || control.report.mutation !== mutation || control.report.linearizable
      || !mutationRefusalObserved(control.report) || control.verdict.outcome !== 'no_go';
  });
  if (controls?.length !== expected.length) failures.push('exactly-one-each');
  return failures.length === 0
    ? { outcome: 'pass', noGo: [], detections: [] }
    : {
        outcome: 'no_go',
        noGo: [{
          kind: 'mmap-not-linearizable',
          detail: `writable negative controls missing or falsely passed: ${failures.join(', ')}`,
        }],
        detections: [],
      };
}

export function classifyRun(
  stage1: Stage1Report | undefined,
  stage2: Stage2Report | undefined,
  crashDetail?: string,
): ProbeVerdict {
  if (stage1 === undefined) {
    return {
      outcome: 'no_go',
      noGo: [{ kind: 'runtime-crash', detail: crashDetail ?? 'probe produced no stage1 evidence' }],
      detections: [],
    };
  }
  if (crashDetail !== undefined) {
    return { outcome: 'no_go', noGo: [{ kind: 'runtime-crash', detail: crashDetail }], detections: [] };
  }
  const noGo: NoGoReason[] = [];
  const detections: Detection[] = [];
  if (!stage1.census.devFuse.exists) {
    noGo.push({ kind: 'fuse-device-absent', detail: stage1.census.devFuse.detail ?? '/dev/fuse not present in the container' });
  }
  if (!stage1.mounted) {
    const attempts = stage1.mountAttempts
      .map((a) => `${a.route}:${a.ok ? 'ok' : `failed${a.errnoName ? ` (${a.errnoName})` : ''}`}`)
      .join(', ');
    noGo.push({ kind: 'mount-refused', detail: `every mount route refused — ${attempts}` });
  }

  if (stage1.mounted) {
    const bootstrap = classifyBootstrap(stage1.bootstrapSamples);
    if (bootstrap?.eager === true) {
      detections.push({
        kind: 'eager-bootstrap',
        detail: `bring-up fits t = ${bootstrap.interceptMs.toFixed(1)}ms + `
          + `${(bootstrap.msPerEntry * 1000).toFixed(1)}µs/entry; linear term dominates at `
          + `${bootstrap.largestEntries} entries`,
      });
    }
    if (stage1.integrity.servedWrongBytes || (!stage1.integrity.refused && !stage1.integrity.errnoName)) {
      detections.push({
        kind: 'range-integrity-missing',
        detail: `poisoned chunk ${stage1.integrity.poisonChunk} was served without refusal`
          + (stage1.integrity.servedWrongBytes ? ' and with wrong bytes' : ''),
      });
    }
    if (!stage1.integrity.digestRefusal.refused) {
      detections.push({
        kind: 'digest-refusal-missing',
        detail: `an entry whose recorded digest mismatches its content was served`
          + `${stage1.integrity.digestRefusal.errnoName ? '' : ' without an error'}`,
      });
    }
  }

  if (stage2 !== undefined && (stage2.cleanup.residueMounts.length > 0 || stage2.cleanup.strayDaemonProcesses !== 0)) {
    detections.push({
      kind: 'mount-residue',
      detail: [
        ...(stage2.cleanup.residueMounts.length === 0
          ? []
          : [`${stage2.cleanup.residueMounts.length} mount line(s) survived cleanup: ${stage2.cleanup.residueMounts.join(' | ')}`]),
        ...(stage2.cleanup.strayDaemonProcesses === 0
          ? []
          : [`${stage2.cleanup.strayDaemonProcesses} FUSE daemon process(es) survived cleanup`]),
      ].join('; '),
    });
  }

  const outcome = noGo.length > 0 ? 'no_go' : detections.length > 0 ? 'defect' : 'pass';
  return { outcome, noGo, detections };
}

/** A run whose container reports a SANDBOX_VERSION other than the configured
 *  image's measured the wrong platform. That verdict replaces any measurement
 *  verdict, and the artifact composer drops every stage cell. */
export function imageMismatchVerdict(identity: RunIdentity | undefined): ProbeVerdict | undefined {
  if (identity === undefined || identity.actualVersion === identity.expectedVersion) return undefined;
  return {
    outcome: 'no_go',
    noGo: [{
      kind: 'image-mismatch',
      detail: `container reports SANDBOX_VERSION ${identity.actualVersion}, configured ${identity.expectedVersion} from ${identity.configuredImage}`,
    }],
    detections: [],
  };
}

/** The artifact record the driver persists for a completed run. */
export interface FuseProbeArtifact {
  readonly schemaVersion: 1;
  readonly command: 'bun scripts/bench-fuse-probe.ts --run';
  readonly runId: string;
  readonly startedAt: string;
  readonly finishedAt: string;
  readonly workerName: string;
  readonly verdict: ProbeVerdict;
  readonly materialization: ProbeVerdict;
  /** The runtime identity this run proved before measuring.
   *  Absent only when failure preceded the first /prepare answer. */
  readonly identity?: RunIdentity;
  /** Absent when deployment/runtime failed before the probe emitted one byte
   *  of evidence, or censored because the run's image identity mismatched.
   *  The artifact's verdict then names which. */
  /** The custom image reference used for stage 3. It is an immutable digest,
   * never a mutable registry tag. */
  readonly writableImage?: string;
  readonly writableMmap: ProbeVerdict;
  readonly stage3?: Stage3Report;
  /** The four real negative binary invocations and their paired C reports. */
  readonly writableControls: readonly WritableMmapControl[];
  readonly stage1?: Stage1Report;
  readonly stage2?: Stage2Report;
  readonly failure?: string;
  readonly cleanupFailure?: string;
}

