/** Generated by `bun scripts/schema-drift.ts --lock` from scripts/schema-genesis.lock.json; the gate refuses a stale copy. */
export const SCHEMA_GENESIS = '0290efab1ebd291ea6b5b8ee6584ddc00642155880655489566cda3f58c5a95d';
