/** Generated by `bun scripts/schema-drift.ts --lock` from scripts/schema-genesis.lock.json; the gate refuses a stale copy. */
export const SCHEMA_GENESIS = 'aa32d7c7c79a85573886ed428b4385af3d8bebc9a73b815acbff63d305d2c13e';
