/** Generated by `bun scripts/schema-drift.ts --lock` from scripts/schema-genesis.lock.json; the gate refuses a stale copy. */
export const SCHEMA_GENESIS = '2d4e8a458cbbce993da303d471023a9418f6906f35a87fe8af1e08eb74e41f8a';
