#!/usr/bin/env bun
// Layer gate — the deterministic, no-LLM per-layer regression report.
//
//   bun scripts/layergate.ts            # per-layer conformance vs the lock
//   bun scripts/layergate.ts --matrix   # fault-injection localization matrix
//   bun scripts/layergate.ts --lock     # re-lock the baselines after an
//                                       # intended behaviour change
//
// Two slices feed one report: core's LAYERS (packages/core/src/layergate) and
// the compaction-ladder slice (packages/compaction/src/layergate.ts — core
// declares that layer but cannot import the package that implements it). The
// script is the only place both sides can meet, so it merges them here; core's
// declared-but-unmeasured placeholder row is replaced by the measured slice.
//
// `unit-layergate.test.ts` (core) and the compaction package's own test run
// the same gates in CI; this is the human-facing view, and the only way to
// re-lock.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  createPipelineSubjects, lockBaseline, LOCKED_BASELINE, LAYERS, FAULTS,
  renderFaultMatrix, renderLayerGateReport, runFaultMatrix, runLayerGate,
  type Baseline, type Fault, type Layer, type LayerGateReport, type PipelineSubjects,
} from '../packages/core/src/index';
import {
  COMPACTION_LAYERS, COMPACTION_FAULTS, COMPACTION_LOCKED_BASELINE,
  createCompactionLadderSubjects, type CompactionLadderSubjects,
} from '../packages/compaction/src/index';
import { createTestRuntime } from '../packages/core/tests/helpers';

const CORE_BASELINE_FILE = join(import.meta.dir, '../packages/core/src/layergate/baseline.ts');
const COMPACTION_BASELINE_FILE = join(import.meta.dir, '../packages/compaction/src/layergate-baseline.ts');

// The gate reads no storage — every prompt probe passes soulOverride — so any
// runtime handle satisfies the one production signature that requires one.
const subjects = createPipelineSubjects(createTestRuntime().rt);
const ladderSubjects = createCompactionLadderSubjects();

// The merged view: every measured probe of both slices, one namespace. Core
// probes read only core subjects and ladder probes only ladder subjects, so
// the spread cannot cross-wire them — but the merged fault matrix CAN prove
// a ladder fault moves no core layer (and vice versa).
type MergedSubjects = PipelineSubjects & CompactionLadderSubjects;
const mergedSubjects: MergedSubjects = { ...subjects, ...ladderSubjects };
const mergedLayers: readonly Layer<MergedSubjects>[] = [
  ...LAYERS.filter((layer) => !(layer.id === 'compaction-ladder' && layer.probes.length === 0)),
  ...COMPACTION_LAYERS,
];
const mergedFaults: readonly Fault<MergedSubjects>[] = [...FAULTS, ...COMPACTION_FAULTS];
const mergedBaseline: Baseline = { ...LOCKED_BASELINE, ...COMPACTION_LOCKED_BASELINE };

function writeBaseline(file: string, header: string[], name: string, baseline: Baseline): void {
  const entries = Object.entries(baseline).map(([id, digest]) => `  '${id}': '${digest}',`).join('\n');
  writeFileSync(file, [
    '/** Generated by `bun run layergate:lock`. Do not edit by hand. */',
    ...header,
    '',
    `export const ${name}: Baseline = {`,
    entries,
    '};',
    '',
  ].join('\n'));
}

if (process.argv.includes('--lock')) {
  const core = await lockBaseline(subjects);
  writeBaseline(CORE_BASELINE_FILE, ["import type { Baseline } from './gate';"], 'LOCKED_BASELINE', core);
  console.log(`Locked ${Object.keys(core).length} core probes → ${CORE_BASELINE_FILE}`);
  const ladder = await lockBaseline(ladderSubjects, COMPACTION_LAYERS);
  writeBaseline(
    COMPACTION_BASELINE_FILE,
    ["import type { Baseline } from '@kinu/core';"],
    'COMPACTION_LOCKED_BASELINE',
    ladder,
  );
  console.log(`Locked ${Object.keys(ladder).length} compaction-ladder probes → ${COMPACTION_BASELINE_FILE}`);
} else if (process.argv.includes('--matrix')) {
  const impacts = await runFaultMatrix(mergedSubjects, mergedFaults, mergedLayers);
  console.log(renderFaultMatrix(impacts));
  process.exitCode = impacts.every((i) => i.localized) ? 0 : 1;
} else {
  const report: LayerGateReport = await runLayerGate({
    subjects: mergedSubjects, baseline: mergedBaseline, layers: mergedLayers,
  });
  console.log(renderLayerGateReport(report));
  process.exitCode = report.layers.every((s) => s.drifted.length === 0 && s.unlocked.length === 0) ? 0 : 1;
}
