#!/usr/bin/env bun
// Layer gate — the deterministic, no-LLM per-layer regression report.
//
//   bun scripts/layergate.ts            # per-layer conformance vs the lock
//   bun scripts/layergate.ts --matrix   # fault-injection localization matrix
//   bun scripts/layergate.ts --lock     # re-lock the baseline after an
//                                       # intended behaviour change
//
// `unit-layergate.test.ts` runs the same gate and the same matrix; this is the
// human-facing view, and the only way to re-lock.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  createPipelineSubjects, lockBaseline, LOCKED_BASELINE,
  renderFaultMatrix, renderLayerGateReport, runFaultMatrix, runLayerGate,
} from '../packages/core/src/index.js';
import { createTestRuntime } from '../packages/core/tests/helpers.js';

const BASELINE_FILE = join(import.meta.dir, '../packages/core/src/layergate/baseline.ts');

// The gate reads no storage — every prompt probe passes soulOverride — so any
// runtime handle satisfies the one production signature that requires one.
const subjects = createPipelineSubjects(createTestRuntime().rt);

if (process.argv.includes('--lock')) {
  const baseline = await lockBaseline(subjects);
  const entries = Object.entries(baseline).map(([id, digest]) => `  '${id}': '${digest}',`).join('\n');
  writeFileSync(BASELINE_FILE, [
    '/** Generated by `bun run layergate:lock`. Do not edit by hand. */',
    "import type { Baseline } from './gate.js';",
    '',
    'export const LOCKED_BASELINE: Baseline = {',
    entries,
    '};',
    '',
  ].join('\n'));
  console.log(`Locked ${Object.keys(baseline).length} probes → ${BASELINE_FILE}`);
} else if (process.argv.includes('--matrix')) {
  const impacts = await runFaultMatrix(subjects);
  console.log(renderFaultMatrix(impacts));
  process.exitCode = impacts.every((i) => i.localized) ? 0 : 1;
} else {
  const report = await runLayerGate({ subjects, baseline: LOCKED_BASELINE });
  console.log(renderLayerGateReport(report));
  process.exitCode = report.layers.every((s) => s.drifted.length === 0 && s.unlocked.length === 0) ? 0 : 1;
}
