import { describe, expect, test } from 'bun:test';
import { gzipSync } from 'node:zlib';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import * as v from 'valibot';
import { PAYLOAD_ARMS, type PayloadArmId } from './fixtures/payload-transport/arms';
import { CLEANUP_GATES, evaluateCleanup, EXIT_RESIDUE, exitFor } from './fixtures/payload-transport/cleanup';
import { decideAll, judgeImage, LOOPBACK_RESIDENCY_NOTE, operationNeedsStart, SDK_THROUGHPUT_CLAIM_NOTE } from './fixtures/payload-transport/decision';
import { isValidResourceName, runIdentity } from './fixtures/payload-transport/payload';
import { renderMarkdown } from './fixtures/payload-transport/report';
import {
  ArtifactSchema,
  validateArtifact,
  type Artifact,
  type Availability,
  type Cell,
} from './fixtures/payload-transport/schema';
import { mulberry32 } from './fixtures/payload-transport/container-harness';
import { wranglerProvesAbsence } from './fixtures/r2-bench/deploy-substrate';

const ROOT = join(dirname(new URL(import.meta.url).pathname));
const FIXTURE_DIR = join(ROOT, 'fixtures/payload-transport');
const workerSource = readFileSync(join(FIXTURE_DIR, 'worker.ts'), 'utf8');
const driverSource = readFileSync(join(ROOT, 'bench-payload-transports.ts'), 'utf8');
const harnessSource = readFileSync(join(FIXTURE_DIR, 'container-harness.ts'), 'utf8');
const configSource = readFileSync(join(FIXTURE_DIR, 'wrangler.jsonc'), 'utf8');

function cell(arm: PayloadArmId, op: 'put' | 'get', sizeMiB: 1 | 10 | 100, wallMs: number | null, status: Cell['status'] = 'ok'): Cell {
  const result: Cell = { arm, op, sizeMiB, rep: 0, phase: status === 'ok' ? 'published' : 'failed', status, wallMs };
  if (status !== 'ok') result.reason = status;
  return result;
}

function artifact(cells: readonly Cell[]): Artifact {
  return validateArtifact({
    instrument: 'payload-transports', version: 1,
    plan: { runId: 'r', workerName: 'kinu-payload-bench-r', bucketName: 'kinu-payload-bench-r', seed: 7, sizesMiB: [1, 10, 100], reps: 1, concurrency: 1, startedAt: '2026-08-26T00:00:00.000Z', imagePinned: 'docker.io/cloudflare/sandbox:0.12.8', imageObserved: '0.12.8' },
    availability: PAYLOAD_ARMS.map((arm) => {
      const row: Availability = { arm, available: arm !== 'temp-s3-creds' };
      if (arm === 'temp-s3-creds') row.reason = 'R2 has no STS';
      return row;
    }),
    cells: [...cells],
    controlRpc: [],
    concurrency: [],
    verdicts: [...decideAll(cells)],
    cleanup: { residue: false, steps: CLEANUP_GATES.map((gate) => ({ gate: gate.name, ok: true, detail: 'clean' })) },
  });
}

describe('payload workload determinism (in-container generator)', () => {
  test('the generator is reproducible from its seed and differs between seeds', () => {
    const nextA = mulberry32(7);
    const nextB = mulberry32(7);
    const nextC = mulberry32(8);
    const a = Array.from({ length: 16 }, nextA);
    expect(a).toEqual(Array.from({ length: 16 }, nextB));
    expect(a).not.toEqual(Array.from({ length: 16 }, nextC));
  });
  test('generated bytes are effectively incompressible and full-range', () => {
    const next = mulberry32(42);
    const bytes = new Uint8Array(256 * 1024);
    for (let i = 0; i < bytes.length; i += 1) bytes[i] = Math.floor(next() * 256);
    expect(gzipSync(bytes).byteLength / bytes.byteLength).toBeGreaterThan(0.99);
  });
  test('every generated Worker and bucket name is legal and unique', () => {
    const a = runIdentity(new Date('2026-08-26T01:02:03Z'), 'abcdef');
    const b = runIdentity(new Date('2026-08-26T01:02:03Z'), '123456');
    expect(isValidResourceName(a.workerName)).toBe(true);
    expect(isValidResourceName(a.bucketName)).toBe(true);
    expect(a.workerName).not.toBe(b.workerName);
    expect(a.bucketName).not.toBe(b.bucketName);
  });
});

describe('one owning DO with container lifecycle', () => {
  test('exactly ONE DurableObject subclass owns the container and the base64 arm', () => {
    const subclasses = [...workerSource.matchAll(/extends (DurableObject|Sandbox)(<[^>]*>)?/g)].map((match) => match[1]);
    expect(subclasses).toEqual(['Sandbox']);
    expect(workerSource).toContain('class PayloadBenchSandbox extends Sandbox');
    expect(workerSource).not.toContain('PayloadBox');
  });
  test('onStart is idempotent readiness: super.onStart first, image verified, harness installed', () => {
    expect(workerSource).toContain('override async onStart(): Promise<void> {\n    await super.onStart();');
    expect(workerSource).toContain("process.env.SANDBOX_VERSION ?? null");
    expect(workerSource).toContain(`'${EXPECTED_IMAGE}'`);
    expect(workerSource).toContain('writeFile(HARNESS_PATH, HARNESS_TS)');
    expect(workerSource).toContain("{ prefix: '/' }");
    expect(workerSource).toContain("mountBucket('BACKUP_BUCKET'");
    expect(workerSource).toContain('await this.reconcileContainer()');
    expect(workerSource).toContain('v.union([v.string(), v.number(), v.boolean()])');
    expect(driverSource).toContain('http://r2.internal/BACKUP_BUCKET/');
    expect(configSource).toContain('"SANDBOX_TRANSPORT": "rpc"');
    expect(workerSource).toContain('invalid request body');
  });
  test('the bundled harness twin is byte-identical to the typed source', () => {
    const twin = readFileSync(join(FIXTURE_DIR, 'container-harness.bundle.txt'), 'utf8');
    expect(twin).toBe(harnessSource);
    expect(configSource).toContain('"type": "Text"');
    expect(configSource).toContain('**/container-harness.bundle.txt');
    expect(workerSource).toContain("import HARNESS_TS from './container-harness.bundle.txt'");
  });
});

describe('deterministic process redrive', () => {
  test('only a MISSING process record starts work; running reads; exited is final', () => {
    expect(operationNeedsStart(null)).toBe(true);
    expect(operationNeedsStart({ exitCode: null })).toBe(false);
    expect(operationNeedsStart({ exitCode: 0 })).toBe(false);
  });
  test('the owner DO keys processes by operationId with autoCleanup disabled', () => {
    expect(workerSource).toContain('operationNeedsStart(existing)');
    expect(workerSource).toContain('processId: operationId');
    expect(workerSource).toContain('autoCleanup: false');
    expect(workerSource).toContain('/op/start');
    expect(workerSource).toContain('/op/poll');
  });
});

describe('credentials never reach a command line or the artifact', () => {
  test('no CLI credential flags exist anywhere in the instrument', () => {
    for (const source of [workerSource, harnessSource, driverSource]) {
      expect(source).not.toContain('--access-key-id');
      expect(source).not.toContain('--secret-access-key');
      expect(source).not.toContain('--session-token');
    }
  });
  test('SigV4 credentials ride in ProcessOptions.env under reserved names only', () => {
    expect(workerSource).toContain('BENCH_R2_ACCESS_KEY_ID: input.accessKeyId');
    expect(harnessSource).toContain("process.env['BENCH_R2_ACCESS_KEY_ID']");
    expect(harnessSource).toContain('world-readable in the container; an\n * environment variable is not');
  });
  test('artifacts carry grant fingerprints, never grant material', () => {
    expect(driverSource).toContain('grantFingerprint');
    // The opaque URL is forwarded to the container as a command argument but
    // never persisted; only its SHA-256 fingerprint reaches the artifact.
    expect(JSON.stringify(validateArtifact(artifact([cell('presigned-r2', 'put', 1, 10)])))).not.toContain('https://');
  });
  test('deploy argv carries non-secret vars only; secrets go through stdin', () => {
    const varMatches = [...driverSource.matchAll(/'--var', `([A-Z_]+):/g)].map((match) => match[1]);
    expect(varMatches).toEqual(['ACCOUNT_ID', 'BUCKET_NAME']);
    expect(driverSource.split('putSecret')[0]).not.toMatch(/'--var', `BENCH_TOKEN|R2_ACCESS_KEY_ID:|R2_SECRET_ACCESS_KEY:/);
    expect(driverSource).toContain("putSecret('BENCH_TOKEN'");
    expect(driverSource).toContain("putSecret('R2_ACCESS_KEY_ID'");
    expect(driverSource).toContain("putSecret('R2_SECRET_ACCESS_KEY'");
  });
  test('secret injection is stdin-only, never argv or captured output', () => {
    const helperIndex = driverSource.indexOf('function putSecret');
    const helper = driverSource.slice(helperIndex, helperIndex + 700);
    expect(helper).toContain("'wrangler', 'secret', 'put'");
    expect(helper).toMatch(/input: `\$\{value\}/);
    expect(helper).toContain("stdio: ['pipe', 'ignore', 'pipe']");
    // The value must never be concatenated into the command array itself.
    expect(helper).not.toMatch(/args.*value/);
  });
  test('the generated wrangler config never carries credential material', () => {
    const start = driverSource.indexOf('function configFor');
    const section = driverSource.slice(start, driverSource.indexOf('}', driverSource.indexOf('r2_buckets', start)));
    expect(section).not.toContain('R2_ACCESS_KEY_ID');
    expect(section).not.toContain('SECRET');
    expect(section).not.toContain('BENCH_TOKEN');
    expect(section).toContain("main: join(FIXTURE_DIR, 'worker.ts')");
  });
});


describe('image freshness censors, never records', () => {
  test('matching image passes; stale and unknown censor', () => {
    expect(judgeImage('docker.io/cloudflare/sandbox:0.12.8', '0.12.8')).toEqual({ kind: 'ok', observed: '0.12.8' });
    expect(judgeImage('docker.io/cloudflare/sandbox:0.12.8', '0.12.7')).toEqual({ kind: 'stale', pinned: 'docker.io/cloudflare/sandbox:0.12.8', observed: '0.12.7' });
    expect(judgeImage('docker.io/cloudflare/sandbox:0.12.8', null)).toEqual({ kind: 'unknown' });
  });
  test('a stale image aborts the run before any seeding', () => {
    const staleIndex = driverSource.indexOf('stale container image');
    const seedIndex = driverSource.indexOf("'/seeds'");
    const setupIndex = driverSource.indexOf("'/setup'");
    expect(staleIndex).toBeGreaterThan(setupIndex);
    expect(seedIndex).toBe(-1); // seeding runs via /op/start now
  });
});

describe('disposable shutdown destroys and orders teardown', () => {
  test('the owner DO DESTROYS the container and clears ephemeral DO state', () => {
    expect(workerSource).toContain('async destroyRun(): Promise<void>');
    expect(workerSource).toContain('await this.destroy()');
    expect(workerSource).toContain('await this.ctx.storage.deleteAll()');
  });
  test('teardown is destroy,destroy,app,worker,bucket,config twice', () => {
    const destroyLoop = driverSource.indexOf('for (const attempt of [1, 2]');
    const destroyCall = driverSource.indexOf("await call(origin, token, '/destroy'");
    const appDelete = driverSource.indexOf('deleteContainerApps(ROOT');
    const workerDelete = driverSource.indexOf('deleteFixtureWorker(');
    const bucketDelete = driverSource.indexOf("'r2', 'bucket', 'delete'");
    const configClear = driverSource.indexOf('rmSync(configPath');
    const twoPassLoop = driverSource.indexOf('for (let pass = 1; pass <= 2; pass += 1)');
    expect(destroyLoop).toBeGreaterThan(-1);
    expect(destroyCall).toBeGreaterThan(destroyLoop);
    expect(twoPassLoop).toBeGreaterThan(destroyCall);
    // One loop body pins the complete release order; pass=1 and pass=2 run it.
    expect(appDelete).toBeGreaterThan(twoPassLoop);
    expect(workerDelete).toBeGreaterThan(appDelete);
    expect(bucketDelete).toBeGreaterThan(workerDelete);
    expect(configClear).toBeGreaterThan(bucketDelete);
  });
  test('container application absence is polled from the account listing', () => {
    expect(driverSource).toContain('containerAppIds(ROOT, [containerApp], log)');
    expect(driverSource).toContain('for (let poll = 0; poll < 6; poll += 1)');
    expect(driverSource).toContain('await delay(10_000)');
  });
  test('a pre-deploy failure proves absence from account deletion, not live RPCs', () => {
    expect(driverSource).not.toContain('fixture never became reachable');
    expect(driverSource).toContain('bucketProofs.length === 2');
    expect(driverSource).toContain('inventoryEmpty || deletionProvedEmpty');
  });

  test('the gate list itself encodes C1..C7 in execution order', () => {
    expect(CLEANUP_GATES.map((gate) => `${gate.id}:${gate.name}`)).toEqual([
      'C1:multipart-ledger-drained',
      'C2:bucket-state-empty',
      'C3:container-application-absent',
      'C4:fixture-worker-absent',
      'C5:bucket-deleted',
      'C6:local-material-cleared',
      'C7:cleanup-replay-idempotent',
    ]);
  });
});

describe('no payload body originates on the driver', () => {
  test('the driver imports no AWS client, generates no bytes, hashes nothing', () => {
    expect(driverSource).not.toContain('AwsClient');
    expect(driverSource).not.toContain('Uint8Array');
    expect(driverSource).not.toContain('createHash');
    expect(driverSource).not.toContain('payloadFor');
    expect(driverSource).not.toContain('mulberry32');
    expect(driverSource).toContain("'/op/start'");
    expect(driverSource).toContain("'/op/poll'");
  });
});

describe('decision honesty', () => {
  test('never ranks unavailable or corrupt arms', () => {
    const cells = [
      cell('do-base64', 'put', 1, 100), cell('do-base64', 'get', 1, 100),
      cell('loopback-entrypoint', 'put', 1, 50), cell('loopback-entrypoint', 'get', 1, 50),
      cell('presigned-r2', 'put', 1, null, 'unavailable'), cell('presigned-r2', 'get', 1, null, 'unavailable'),
      cell('temp-s3-creds', 'put', 1, null, 'corrupt'), cell('temp-s3-creds', 'get', 1, null, 'corrupt'),
    ];
    const verdict = decideAll(cells).find((entry) => entry.sizeMiB === 1)!;
    expect(verdict.kind).toBe('ranking');
    if (verdict.kind === 'ranking') {
      expect(verdict.ranked.map((row) => row.arm)).toEqual(['loopback-entrypoint', 'do-base64']);
      expect(verdict.exclusions.map((entry) => entry.arm).sort()).toEqual(['presigned-r2', 'temp-s3-creds']);
    }
  });
  test('a single clean arm produces no ranking', () => {
    const verdict = decideAll([cell('do-base64', 'put', 1, 100), cell('do-base64', 'get', 1, 100)]).find((entry) => entry.sizeMiB === 1)!;
    expect(verdict.kind).toBe('no-ranking');
  });
  test('validates embedded shared UploadIntent contracts rather than a copied shape', () => {
    const invalid = {
      instrument: 'payload-transports', version: 1,
      plan: { runId: 'r', workerName: 'w', bucketName: 'b', seed: 1, sizesMiB: [1], reps: 1, concurrency: 1, startedAt: '2026-08-26T00:00:00.000Z' },
      availability: [], controlRpc: [], concurrency: [], verdicts: [], cleanup: { residue: false, steps: [] },
      cells: [{ ...cell('do-base64', 'put', 1, 10), uploadIntent: { operationId: 'op', attemptId: 'attempt', boxId: 'box', epoch: '0', exactKey: 'key', method: 'PUT', byteLength: '1', sha256: 'NOT-A-DIGEST', expiresAt: '1' } }],
    };
    expect(() => v.parse(ArtifactSchema, invalid)).toThrow();
  });
});

describe('report honesty and cleanup admission', () => {
  test('renders every required disclosure', () => {
    const text = renderMarkdown(artifact([cell('do-base64', 'put', 1, 10), cell('do-base64', 'get', 1, 10)]));
    expect(text).toContain(SDK_THROUGHPUT_CLAIM_NOTE);
    expect(text).toContain(LOOPBACK_RESIDENCY_NOTE);
    expect(text).toContain('CPU per arm is UNKNOWN');
    expect(text).toContain('no payload body ever originated on it');
  });
  test('missing evidence is residue and forces a nonzero exit', () => {
    const cleanup = evaluateCleanup([{ gate: 'bucket-deleted', ok: true, detail: 'deleted' }]);
    expect(cleanup.residue).toBe(true);
    expect(exitFor(null, cleanup)).toBe(EXIT_RESIDUE);
  });
  test('complete clean evidence is accepted and replay-safe', () => {
    const evidence = CLEANUP_GATES.map((gate) => ({ gate: gate.name, ok: true, detail: 'absent on first and replay pass' }));
    expect(evaluateCleanup(evidence).residue).toBe(false);
  });
  test('a later cleanup failure cannot hide behind an earlier success', () => {
    const evidence = CLEANUP_GATES.map((gate) => ({ gate: gate.name, ok: true, detail: 'first pass clean' }));
    evidence.push({ gate: 'container-application-absent', ok: false, detail: 'account listing failed' });
    const verdict = evaluateCleanup(evidence);
    expect(verdict.residue).toBe(true);
    expect(verdict.failedGates).toContain('container-application-absent');
  });
  test('only explicit absence proves a failed wrangler delete is clean', () => {
    expect(wranglerProvesAbsence('WRANGLER_FAILED: Authentication error')).toBe(false);
    expect(wranglerProvesAbsence('WRANGLER_FAILED: network timeout')).toBe(false);
    expect(wranglerProvesAbsence('WRANGLER_FAILED: Worker not found')).toBe(true);
    expect(wranglerProvesAbsence('deleted')).toBe(true);
  });
  test('destroy or account-listing failure makes C3 residue even if another C3 row passes', () => {
    const base = CLEANUP_GATES.map((gate) => ({ gate: gate.name, ok: true, detail: 'clean' }));
    for (const detail of ['destroy attempt 2: Durable Object reset', 'container listing failed: API timeout']) {
      const verdict = evaluateCleanup([...base, { gate: 'container-application-absent', ok: false, detail }]);
      expect(verdict.residue).toBe(true);
      expect(verdict.failedGates).toContain('container-application-absent');
    }
  });
});

const EXPECTED_IMAGE = '0.12.8';
