import { describe, expect, test } from 'bun:test';
import { gzipSync } from 'node:zlib';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import * as v from 'valibot';
import {
  PAYLOAD_ARMS,
  PAYLOAD_SIZES_MIB,
  type PayloadArmId,
  type PayloadSizeMiB,
} from './fixtures/payload-transport/arms';
import { CLEANUP_GATES, evaluateCleanup, EXIT_RESIDUE, exitFor } from './fixtures/payload-transport/cleanup';
import { decideAll, judgeImage, LOOPBACK_RESIDENCY_NOTE, operationNeedsStart, SDK_THROUGHPUT_CLAIM_NOTE } from './fixtures/payload-transport/decision';
import { isValidResourceName, runIdentity } from './fixtures/payload-transport/payload';
import { renderMarkdown } from './fixtures/payload-transport/report';
import {
  ArtifactSchema,
  validateArtifact,
  type Artifact,
  type Availability,
  type Cell,
} from './fixtures/payload-transport/schema';
import { mulberry32 } from './fixtures/payload-transport/container-harness';
import { wranglerProvesAbsence } from './fixtures/r2-bench/deploy-substrate';
import { withAuthoritativeBucket } from './bench-payload-transports';
import { isProductSource, readMatching } from './sources';

const ROOT = join(dirname(new URL(import.meta.url).pathname));
const FIXTURE_DIR = join(ROOT, 'fixtures/payload-transport');
// The instrument runs only against a live account, so the properties below
// that have no behavioural surface here — a credential never spelled on a
// command line, a driver that holds no payload, a bundle that matches its
// source, a product tree that never imports the relay — are read off the
// sources. Everything else about the instrument is asserted by running it.
const workerSource = readFileSync(join(FIXTURE_DIR, 'worker.ts'), 'utf8');
const driverSource = readFileSync(join(ROOT, 'bench-payload-transports.ts'), 'utf8');
const harnessSource = readFileSync(join(FIXTURE_DIR, 'container-harness.ts'), 'utf8');

/** The tier these unit fixtures are written at. Whichever tier the instrument
 *  runs first: these tests are about ranking, redaction and schema shape, none
 *  of which depend on the size — so they take one from the list rather than
 *  naming a number the list can stop containing. */
const TIER = PAYLOAD_SIZES_MIB[0];

function cell(arm: PayloadArmId, op: 'put' | 'get', sizeMiB: PayloadSizeMiB, wallMs: number | null, status: Cell['status'] = 'ok'): Cell {
  const result: Cell = { arm, op, sizeMiB, rep: 0, phase: status === 'ok' ? 'published' : 'failed', status, wallMs };
  if (status !== 'ok') result.reason = status;
  return result;
}

function artifact(cells: readonly Cell[], warmups: readonly Cell[] = []): Artifact {
  return validateArtifact({
    instrument: 'payload-transports', version: 1,
    plan: { runId: 'r', workerName: 'kinu-payload-bench-r', bucketName: 'kinu-payload-bench-r', seed: 7, sizesMiB: [...PAYLOAD_SIZES_MIB], reps: 1, concurrency: 1, startedAt: '2026-08-26T00:00:00.000Z', imagePinned: 'docker.io/cloudflare/sandbox:0.12.8', imageObserved: '0.12.8' },
    availability: PAYLOAD_ARMS.map((arm) => {
      const row: Availability = { arm, available: arm !== 'temp-s3-creds' };
      if (arm === 'temp-s3-creds') row.reason = 'R2 has no STS';
      return row;
    }),
    warmups: [...warmups],
    cells: [...cells],
    controlRpc: [],
    concurrency: [],
    verdicts: [...decideAll(cells)],
    cleanup: { residue: false, steps: CLEANUP_GATES.map((gate) => ({ gate: gate.name, ok: true, detail: 'clean' })) },
  });
}

describe('payload workload determinism (in-container generator)', () => {
  test('the generator is reproducible from its seed and differs between seeds', () => {
    const nextA = mulberry32(7);
    const nextB = mulberry32(7);
    const nextC = mulberry32(8);
    const a = Array.from({ length: 16 }, nextA);
    expect(a).toEqual(Array.from({ length: 16 }, nextB));
    expect(a).not.toEqual(Array.from({ length: 16 }, nextC));
  });
  test('generated bytes are effectively incompressible and full-range', () => {
    const next = mulberry32(42);
    const bytes = new Uint8Array(256 * 1024);
    for (let i = 0; i < bytes.length; i += 1) bytes[i] = Math.floor(next() * 256);
    expect(gzipSync(bytes).byteLength / bytes.byteLength).toBeGreaterThan(0.99);
  });
  test('every generated Worker and bucket name is legal and unique', () => {
    const a = runIdentity(new Date('2026-08-26T01:02:03Z'), 'abcdef');
    const b = runIdentity(new Date('2026-08-26T01:02:03Z'), '123456');
    expect(isValidResourceName(a.workerName)).toBe(true);
    expect(isValidResourceName(a.bucketName)).toBe(true);
    expect(a.workerName).not.toBe(b.workerName);
    expect(a.bucketName).not.toBe(b.bucketName);
  });
});

describe('the owning-DO arm measures the shape devbox had, not a fresh reassembly', () => {
  test('no product source reaches back for the relay', () => {
    // This is the property the removal bought: a devbox that carries payload
    // through its own isolate is the defect a store mount replaced. The
    // fixture keeps the shape so the baseline stays measurable, and an import
    // of it from packages/ would put the shape back in the product.
    //
    // AN IMPORT, NOT A MENTION. `object-store.ts` says in prose where its
    // upload went, which is the sentence a reader needs and is not a
    // dependency; a substring scan would report that sentence as the defect
    // and would then have to be relaxed to pass, which is how a gate loses its
    // teeth on the day it is written.
    const reaches = /from\s+'[^']*isolate-relay'|import\(\s*'[^']*isolate-relay'\s*\)/;
    const importers = [...readMatching(isProductSource)]
      .filter(([, text]) => reaches.test(text))
      .map(([file]) => file);
    expect(importers).toEqual([]);
  });
});

describe('benchmark bucket authority', () => {
  test('an explicit bucket is used exactly, without generated-name or discovery fallback', () => {
    const generated = runIdentity(new Date('2026-08-30T00:00:00Z'), 'abcdef');
    const named = withAuthoritativeBucket(generated, 'kinu-payload-bench-final-20260830');
    expect(named.bucketName).toBe('kinu-payload-bench-final-20260830');
    expect(named.workerName).toBe(generated.workerName);
    expect(withAuthoritativeBucket(generated, undefined)).toBe(generated);
  });
});

describe('one owning DO with container lifecycle', () => {
  test('the harness source is bundled once and matches its typed source', () => {
    const twin = readFileSync(join(FIXTURE_DIR, 'container-harness.bundle.txt'), 'utf8');
    expect(twin).toBe(harnessSource);
  });
});

describe('deterministic process redrive', () => {
  test('only a MISSING process record starts work; running reads; exited is final', () => {
    expect(operationNeedsStart(null)).toBe(true);
    expect(operationNeedsStart({ exitCode: null })).toBe(false);
    expect(operationNeedsStart({ exitCode: 0 })).toBe(false);
  });
});

describe('credentials never reach a command line or the artifact', () => {
  test('no CLI credential flags exist anywhere in the instrument', () => {
    for (const source of [workerSource, harnessSource, driverSource]) {
      expect(source).not.toContain('--access-key-id');
      expect(source).not.toContain('--secret-access-key');
      expect(source).not.toContain('--session-token');
    }
  });
  test('artifacts carry grant fingerprints, never grant material', () => {
    // The opaque URL is forwarded to the container as a command argument but
    // never persisted; only its SHA-256 fingerprint reaches the artifact.
    expect(JSON.stringify(validateArtifact(artifact([cell('presigned-r2', 'put', TIER, 10)])))).not.toContain('https://');
  });
  test('deploy argv carries non-secret vars only', () => {
    const varMatches = [...driverSource.matchAll(/'--var', `([A-Z_]+):/g)].map((match) => match[1]);
    expect(varMatches).toEqual(['ACCOUNT_ID', 'BUCKET_NAME']);
  });
  test('the generated wrangler config never carries credential material', () => {
    const start = driverSource.indexOf('function configFor');
    const section = driverSource.slice(start, driverSource.indexOf('}', driverSource.indexOf('r2_buckets', start)));
    expect(section).not.toContain('R2_ACCESS_KEY_ID');
    expect(section).not.toContain('SECRET');
    expect(section).not.toContain('BENCH_TOKEN');
  });
});


describe('image freshness censors, never records', () => {
  test('matching image passes; stale and unknown censor', () => {
    expect(judgeImage('docker.io/cloudflare/sandbox:0.12.8', '0.12.8')).toEqual({ kind: 'ok', observed: '0.12.8' });
    expect(judgeImage('docker.io/cloudflare/sandbox:0.12.8', '0.12.7')).toEqual({ kind: 'stale', pinned: 'docker.io/cloudflare/sandbox:0.12.8', observed: '0.12.7' });
    expect(judgeImage('docker.io/cloudflare/sandbox:0.12.8', null)).toEqual({ kind: 'unknown' });
  });
});

describe('disposable shutdown destroys and orders teardown', () => {
  test('the gate list itself encodes C1..C7 in execution order', () => {
    expect(CLEANUP_GATES.map((gate) => `${gate.id}:${gate.name}`)).toEqual([
      'C1:multipart-ledger-drained',
      'C2:bucket-state-empty',
      'C3:container-application-absent',
      'C4:fixture-worker-absent',
      'C5:bucket-deleted',
      'C6:local-material-cleared',
      'C7:cleanup-replay-idempotent',
    ]);
  });
});

describe('no payload body originates on the driver', () => {
  test('the driver imports no AWS client, generates no bytes, hashes nothing', () => {
    // The report discloses that no payload body ever originated on the driver
    // (`renderMarkdown`, asserted below); this is what makes that sentence
    // true, and the instrument cannot run here to show it.
    expect(driverSource).not.toContain('AwsClient');
    expect(driverSource).not.toContain('Uint8Array');
    expect(driverSource).not.toContain('createHash');
    expect(driverSource).not.toContain('payloadFor');
    expect(driverSource).not.toContain('mulberry32');
  });
});

describe('decision honesty', () => {
  test('never ranks unavailable or corrupt arms', () => {
    const cells = [
      cell('do-base64', 'put', TIER, 100), cell('do-base64', 'get', TIER, 100),
      cell('loopback-entrypoint', 'put', TIER, 50), cell('loopback-entrypoint', 'get', TIER, 50),
      cell('presigned-r2', 'put', TIER, null, 'unavailable'), cell('presigned-r2', 'get', TIER, null, 'unavailable'),
      cell('temp-s3-creds', 'put', TIER, null, 'corrupt'), cell('temp-s3-creds', 'get', TIER, null, 'corrupt'),
    ];
    const verdict = decideAll(cells).find((entry) => entry.sizeMiB === TIER)!;
    expect(verdict.kind).toBe('ranking');
    if (verdict.kind === 'ranking') {
      expect(verdict.ranked.map((row) => row.arm)).toEqual(['loopback-entrypoint', 'do-base64']);
      expect(verdict.exclusions.map((entry) => entry.arm).sort()).toEqual(['presigned-r2', 'temp-s3-creds']);
    }
  });
  test('a single clean arm produces no ranking', () => {
    const verdict = decideAll([cell('do-base64', 'put', TIER, 100), cell('do-base64', 'get', TIER, 100)]).find((entry) => entry.sizeMiB === TIER)!;
    expect(verdict.kind).toBe('no-ranking');
  });
  test('records warm-up evidence separately from statistic samples and ranking', () => {
    const samples = [
      cell('do-base64', 'put', TIER, 100), cell('do-base64', 'get', TIER, 100),
      cell('loopback-entrypoint', 'put', TIER, 50), cell('loopback-entrypoint', 'get', TIER, 50),
    ];
    const warmups = [
      cell('do-base64', 'put', TIER, 10_000), cell('do-base64', 'get', TIER, 10_000),
    ];
    const observed = artifact(samples, warmups);
    expect(observed.cells).toHaveLength(samples.length);
    expect(observed.warmups).toEqual(warmups);
    const verdict = decideAll(observed.cells).find((entry) => entry.sizeMiB === TIER)!;
    expect(verdict.kind).toBe('ranking');
    if (verdict.kind === 'ranking') {
      expect(verdict.ranked.map((row) => row.arm)).toEqual(['loopback-entrypoint', 'do-base64']);
    }
  });
  test('validates embedded shared UploadIntent contracts rather than a copied shape', () => {
    // Valid in every field but the digest, so the refusal below is the shared
    // UploadIntent rule and not an earlier plan field: the fixture used to
    // carry an off-list tier and passed on that instead.
    const invalid = {
      instrument: 'payload-transports', version: 1,
      plan: { runId: 'r', workerName: 'w', bucketName: 'b', seed: 1, sizesMiB: [...PAYLOAD_SIZES_MIB], reps: 1, concurrency: 1, startedAt: '2026-08-26T00:00:00.000Z' },
      availability: [], warmups: [], controlRpc: [], concurrency: [], verdicts: [], cleanup: { residue: false, steps: [] },
      cells: [{ ...cell('do-base64', 'put', TIER, 10), uploadIntent: { operationId: 'op', attemptId: 'attempt', boxId: 'box', epoch: '0', exactKey: 'key', method: 'PUT', byteLength: '1', sha256: 'NOT-A-DIGEST', expiresAt: '1' } }],
    };
    expect(() => v.parse(ArtifactSchema, invalid)).toThrow('Expected a lowercase SHA-256 digest');
  });
});

describe('report honesty and cleanup admission', () => {
  test('renders every required disclosure', () => {
    const text = renderMarkdown(artifact([cell('do-base64', 'put', TIER, 10), cell('do-base64', 'get', TIER, 10)]));
    expect(text).toContain(SDK_THROUGHPUT_CLAIM_NOTE);
    expect(text).toContain(LOOPBACK_RESIDENCY_NOTE);
    expect(text).toContain('CPU per arm is UNKNOWN');
    expect(text).toContain('no payload body ever originated on it');
  });
  test('missing evidence is residue and forces a nonzero exit', () => {
    const cleanup = evaluateCleanup([{ gate: 'bucket-deleted', ok: true, detail: 'deleted' }]);
    expect(cleanup.residue).toBe(true);
    expect(exitFor(null, cleanup)).toBe(EXIT_RESIDUE);
  });
  test('complete clean evidence is accepted and replay-safe', () => {
    const evidence = CLEANUP_GATES.map((gate) => ({ gate: gate.name, ok: true, detail: 'absent on first and replay pass' }));
    expect(evaluateCleanup(evidence).residue).toBe(false);
  });
  test('a later cleanup failure cannot hide behind an earlier success', () => {
    const evidence = CLEANUP_GATES.map((gate) => ({ gate: gate.name, ok: true, detail: 'first pass clean' }));
    evidence.push({ gate: 'container-application-absent', ok: false, detail: 'account listing failed' });
    const verdict = evaluateCleanup(evidence);
    expect(verdict.residue).toBe(true);
    expect(verdict.failedGates).toContain('container-application-absent');
  });
  test('only explicit absence proves a failed wrangler delete is clean', () => {
    expect(wranglerProvesAbsence('WRANGLER_FAILED: Authentication error')).toBe(false);
    expect(wranglerProvesAbsence('WRANGLER_FAILED: network timeout')).toBe(false);
    expect(wranglerProvesAbsence('WRANGLER_FAILED: Worker not found')).toBe(true);
    expect(wranglerProvesAbsence('deleted')).toBe(true);
  });
  test('destroy or account-listing failure makes C3 residue even if another C3 row passes', () => {
    const base = CLEANUP_GATES.map((gate) => ({ gate: gate.name, ok: true, detail: 'clean' }));
    for (const detail of ['destroy attempt 2: Durable Object reset', 'container listing failed: API timeout']) {
      const verdict = evaluateCleanup([...base, { gate: 'container-application-absent', ok: false, detail }]);
      expect(verdict.residue).toBe(true);
      expect(verdict.failedGates).toContain('container-application-absent');
    }
  });
});

