/**
 * The install scanner ships as a BUILT bundle, and this gate keeps it honest.
 *
 * Bun loads `[install.security] scanner` BEFORE it installs anything, so the
 * file it loads cannot import a dependency: on a fresh checkout the install
 * dies with `SecurityScannerNotInDependencies` having unpacked four tarballs.
 * That one import of `valibot` kept every GitHub workflow red at "Install
 * dependencies" until 2026-09-02, and `setup-worktree.sh` hid the same deadlock
 * locally by symlinking valibot in by hand. A package-name scanner has the same
 * deadlock — measured: `is configured in bunfig.toml but is not installed`.
 *
 * The source, `scripts/security-scanner.ts`, keeps its decoder — the anti-slop
 * rules forbid hand-rolled narrowing of boundary input, and a scanner is a
 * boundary. What Bun loads is `scripts/security-scanner.bundle.js`: the same
 * source with the decoder inlined by `bun build`, committed because the
 * bootstrap needs it before any build step could run. A committed build output
 * drifts from its source the day nobody rebuilds it, so this gate rebuilds the
 * bundle in memory on every run and refuses a byte that differs.
 *
 * `--write` is the one way the bundle is produced (`bun run build:scanner`), so
 * the gate and the builder cannot disagree about what "fresh" means.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { finding } from './gate-ratchet';

const REPO_ROOT = join(import.meta.dir, '..');

export const GATE = 'scanner-bundle';

export const SCANNER_SOURCE = 'scripts/security-scanner.ts';

/** What `bunfig.toml` must name, exactly — the bundle, never the source. */
export const SCANNER_BUNDLE = 'scripts/security-scanner.bundle.js';

export const BUNDLE_BANNER =
  `// GENERATED by \`bun run build:scanner\` from ${SCANNER_SOURCE}. Do not edit.\n`
  + '// Bun loads the install scanner before it installs anything, so the scanner\n'
  + '// cannot import a dependency; this bundle carries its decoder inlined.';

/** A bare import is a dependency the bootstrap cannot satisfy. */
const BARE_IMPORT = /^\s*import\b[^'"]*['"](?![./])/mu;

/** The bundle as `bun build` produces it from the source, in memory. */
export async function buildScannerBundle(root: string = REPO_ROOT): Promise<string> {
  const built = await Bun.build({
    entrypoints: [join(root, SCANNER_SOURCE)],
    target: 'bun',
    format: 'esm',
    banner: BUNDLE_BANNER,
  });
  if (!built.success) {
    throw new Error(`building ${SCANNER_SOURCE}: ${built.logs.map((log) => log.message).join('; ')}`);
  }
  const [artifact] = built.outputs;
  if (artifact === undefined) throw new Error(`building ${SCANNER_SOURCE} produced no output`);
  return artifact.text();
}

export interface BundleVerdict {
  readonly findings: readonly string[];
  readonly bytes: number;
}

/** Judge a committed bundle against a fresh build and the bunfig wiring. */
export function judgeBundle(committed: string, fresh: string, bunfig: string): BundleVerdict {
  const findings: string[] = [];
  if (committed !== fresh) {
    findings.push(finding({
      invariant: `${SCANNER_BUNDLE} is byte-identical to a fresh build of ${SCANNER_SOURCE}`,
      at: SCANNER_BUNDLE,
      found: `${String(committed.length)} committed byte(s) against ${String(fresh.length)} freshly built`,
      silently: 'every `bun install` and `bun pm scan` runs the STALE scanner: a reviewed advisory '
        + 'added to the source, or a decoder fix, never reaches the check that guards installs',
      fix: 'bun run build:scanner   # then commit the bundle beside the source',
    }));
  }
  if (BARE_IMPORT.test(fresh)) {
    findings.push(finding({
      invariant: `${SCANNER_BUNDLE} imports nothing outside itself`,
      at: SCANNER_BUNDLE,
      found: 'a bare import specifier survived bundling',
      silently: 'a fresh checkout cannot install: Bun loads the scanner before any dependency '
        + 'exists and dies with SecurityScannerNotInDependencies',
      fix: `remove the external import from ${SCANNER_SOURCE} or mark it bundleable`,
    }));
  }
  if (!bunfig.split('\n').some((line) => new RegExp(`^scanner\\s*=\\s*"\\./${SCANNER_BUNDLE}"`, 'u').test(line))) {
    findings.push(finding({
      invariant: `bunfig.toml [install.security] scanner is "./${SCANNER_BUNDLE}"`,
      at: 'bunfig.toml [install.security]',
      found: 'a different scanner path, or none',
      silently: 'the bundle this gate keeps fresh is not the file Bun loads',
      fix: `set scanner = "./${SCANNER_BUNDLE}" in bunfig.toml`,
    }));
  }
  return { findings, bytes: fresh.length };
}

async function main(args: readonly string[]): Promise<number> {
  const fresh = await buildScannerBundle();
  const bundlePath = join(REPO_ROOT, SCANNER_BUNDLE);
  if (args.includes('--write')) {
    writeFileSync(bundlePath, fresh);
    console.log(`${GATE}: wrote ${SCANNER_BUNDLE} — ${String(fresh.length)} bytes from ${SCANNER_SOURCE}`);
    return 0;
  }
  const committed = readFileSync(bundlePath, 'utf8');
  const bunfig = readFileSync(join(REPO_ROOT, 'bunfig.toml'), 'utf8');
  const verdict = judgeBundle(committed, fresh, bunfig);
  if (verdict.findings.length > 0) {
    console.error(`${GATE}: ${String(verdict.findings.length)} finding(s)\n`);
    for (const each of verdict.findings) console.error(each);
    return 1;
  }
  console.log(
    `${GATE}: ok — ${SCANNER_BUNDLE} is a fresh build of ${SCANNER_SOURCE} (${String(verdict.bytes)} bytes), `
    + 'imports nothing, and is the scanner bunfig.toml names',
  );
  console.log(`  blind: whether the bundled decoder behaves as the source — that is scripts/dependency-advisory-gate.ts, at the ci tier, over a real \`bun pm scan\``);
  return 0;
}

if (import.meta.main) process.exit(await main(process.argv.slice(2)));
